"""Taken from,
https://en.wikipedia.org/wiki/List_of_countries_and_dependencies_by_population
2022-09-20
"""

countries = [
    "China",
    "India",
    "United States",
    "Indonesia",
    "Pakistan",
    "Nigeria",
    "Brazil",
    "Bangladesh",
    "Russia",
    "Mexico",
    "Japan",
    "Philippines",
    "Ethiopia",
    "Egypt",
    "Vietnam",
    "DR Congo",
    "Iran",
    "Turkey",
    "Germany",
    "France",
    "United Kingdom",
    "Thailand",
    "South Africa",
    "Tanzania",
    "Italy",
    "Myanmar",
    "South Korea",
    "Colombia",
    "Kenya",
    "Spain",
    "Argentina",
    "Algeria",
    "Sudan",
    "Uganda",
    "Iraq",
    "Ukraine",
    "Canada",
    "Poland",
    "Morocco",
    "Uzbekistan",
    "Saudi Arabia",
    "Peru",
    "Angola",
    "Afghanistan",
    "Malaysia",
    "Mozambique",
    "Yemen",
    "Ghana",
    "Ivory Coast",
    "Venezuela",
    "Nepal",
    "Madagascar",
    "Australia",
    "North Korea",
    "Cameroon",
    "Niger",
    "Taiwan",
    "Sri Lanka",
    "Burkina Faso",
    "Malawi",
    "Mali",
    "Chile",
    "Kazakhstan",
    "Romania",
    "Zambia",
    "Syria",
    "Ecuador",
    "Netherlands",
    "Senegal",
    "Guatemala",
    "Chad",
    "Somalia",
    "Cambodia",
    "Zimbabwe",
    "South Sudan",
    "Rwanda",
    "Guinea",
    "Burundi",
    "Benin",
    "Tunisia",
    "Bolivia",
    "Haiti",
    "Belgium",
    "Jordan",
    "Cuba",
    "Dominican Republic",
    "Czech Republic",
    "Sweden",
    "Greece",
    "Portugal",
    "Azerbaijan",
    "Hungary",
    "Israel",
    "Honduras",
    "Tajikistan",
    "United Arab Emirates",
    "Belarus",
    "Papua New Guinea",
    "Austria",
    "Switzerland",
    "Sierra Leone",
    "Togo",
    "Hong Kong (China)",
    "Paraguay",
    "Laos",
    "Libya",
    "El Salvador",
    "Serbia",
    "Lebanon",
    "Kyrgyzstan",
    "Nicaragua",
    "Bulgaria",
    "Turkmenistan",
    "Denmark",
    "Congo",
    "Central African Republic",
    "Finland",
    "Singapore",
    "Norway",
    "Slovakia",
    "Palestine",
    "Costa Rica",
    "New Zealand",
    "Ireland",
    "Kuwait",
    "Liberia",
    "Oman",
    "Panama",
    "Mauritania",
    "Croatia",
    "Georgia",
    "Eritrea",
    "Uruguay",
    "Mongolia",
    "Bosnia and Herzegovina",
    "Puerto Rico (United States)",
    "Armenia",
    "Lithuania",
    "Albania",
    "Qatar",
    "Jamaica",
    "Moldova",
    "Namibia",
    "Gambia",
    "Botswana",
    "Gabon",
    "Lesotho",
    "Slovenia",
    "Latvia",
    "North Macedonia",
    "Kosovo",
    "Guinea-Bissau",
    "Equatorial Guinea",
    "Bahrain",
    "Trinidad and Tobago",
    "Estonia",
    "East Timor",
    "Mauritius",
    "Eswatini",
    "Djibouti",
    "Cyprus",
    "Fiji",
    "Comoros",
    "Bhutan",
    "Guyana",
    "Solomon Islands",
    "Macau (China)",
    "Luxembourg",
    "Montenegro",
    "Western Sahara",
    "Suriname",
    "Cape Verde",
    "Malta",
    "Belize",
    "Brunei",
    "Bahamas",
    "Maldives",
    "Northern Cyprus",
    "Iceland",
    "Transnistria",
    "Vanuatu",
    "Barbados",
    "French Polynesia (France)",
    "New Caledonia (France)",
    "Abkhazia",
    "São Tomé and Príncipe",
    "Samoa",
    "Saint Lucia",
    "Guam (United States)",
    "Curaçao (Netherlands)",
    "Artsakh",
    "Kiribati",
    "Grenada",
    "Aruba (Netherlands)",
    "Saint Vincent and the Grenadines",
    "Jersey (British Crown Dependency)",
    "Micronesia",
    "Tonga",
    "Antigua and Barbuda",
    "Seychelles",
    "U.S. Virgin Islands (United States)",
    "Isle of Man (British Crown Dependency)",
    "Andorra",
    "Dominica",
    "Cayman Islands (United Kingdom)",
    "Bermuda (United Kingdom)",
    "Guernsey (British Crown Dependency)",
    "Greenland (Denmark)",
    "Marshall Islands",
    "Saint Kitts and Nevis",
    "Faroe Islands (Denmark)",
    "South Ossetia",
    "American Samoa (United States)",
    "Northern Mariana Islands (United States)",
    "Turks and Caicos Islands (United Kingdom)",
    "Sint Maarten (Netherlands)",
    "Liechtenstein",
    "Monaco",
    "Gibraltar (United Kingdom)",
    "San Marino",
    "Saint Martin (France)",
    "Åland (Finland)",
    "British Virgin Islands (United Kingdom)",
    "Palau",
    "Cook Islands",
    "Anguilla (United Kingdom)",
    "Nauru",
    "Wallis and Futuna (France)",
    "Tuvalu",
    "Saint Barthélemy (France)",
    "Saint Helena, Ascension and Tristan da Cunha (United Kingdom)",
    "Saint Pierre and Miquelon (France)",
    "Montserrat (United Kingdom)",
    "Falkland Islands (United Kingdom)",
    "Christmas Island (Australia)",
    "Norfolk Island (Australia)",
    "Niue (New Zealand)",
    "Tokelau (New Zealand)",
    "Vatican City",
    "Cocos (Keeling) Islands (Australia)",
    "Pitcairn Islands (United Kingdom)",
]
